"""
This type stub file was generated by pyright.
"""

from google.api_core import version as api_core_version

"""Google API Core.

This package contains common code and utilties used by Google client libraries.
"""
__version__ = ...
