"""
This type stub file was generated by pyright.
"""

import os
from google.cloud import _http

"""Create / interact with Google Cloud Storage connections."""
if os.getenv("GOOGLE_API_USE_CLIENT_CERTIFICATE") == "true":
    release = ...

class Connection(_http.JSONConnection):
    """A connection to Google Cloud Storage via the JSON REST API. Mutual TLS feature will be
    enabled if `GOOGLE_API_USE_CLIENT_CERTIFICATE` environment variable is set to "true".

    :type client: :class:`~google.cloud.storage.client.Client`
    :param client: The client that owns the current connection.

    :type client_info: :class:`~google.api_core.client_info.ClientInfo`
    :param client_info: (Optional) instance used to generate user agent.

    :type api_endpoint: str
    :param api_endpoint: (Optional) api endpoint to use.
    """

    DEFAULT_API_ENDPOINT = ...
    DEFAULT_API_MTLS_ENDPOINT = ...
    def __init__(self, client, client_info=..., api_endpoint=...) -> None: ...
    API_VERSION = ...
    API_URL_TEMPLATE = ...
    def api_request(self, *args, **kwargs): ...
