"""
This type stub file was generated by pyright.
"""

"""Firebase Cloud Storage module.

This module contains utilities for accessing Google Cloud Storage buckets associated with
Firebase apps. This requires the ``google-cloud-storage`` Python module.
"""
from typing import Optional

from firebase_admin import App
from google.cloud import storage

_STORAGE_ATTRIBUTE = ...

def bucket(name: Optional[str] = ..., app: Optional[App] = ...) -> storage.Bucket:
    """Returns a handle to a Google Cloud Storage bucket.

    If the name argument is not provided, uses the 'storageBucket' option specified when
    initializing the App. If that is also not available raises an error. This function
    does not make any RPC calls.

    Args:
      name: Name of a cloud storage bucket (optional).
      app: An App instance (optional).

    Returns:
      google.cloud.storage.Bucket: A handle to the specified bucket.

    Raises:
      ValueError: If a bucket name is not specified either via options or method arguments,
          or if the specified bucket name is not a valid string.
    """
    ...

class _StorageClient:
    """Holds a Google Cloud Storage client instance."""

    def __init__(self, credentials, project, default_bucket) -> None: ...
    @classmethod
    def from_app(cls, app): ...
    def bucket(self, name=...):  # -> Bucket:
        """Returns a handle to the specified Cloud Storage Bucket."""
        ...
