"""
This type stub file was generated by pyright.
"""

"""Exceptions used in the google.auth package."""

class GoogleAuthError(Exception):
    """Base class for all google.auth errors."""

    ...

class TransportError(GoogleAuthError):
    """Used to indicate an error occurred during an HTTP request."""

    ...

class RefreshError(GoogleAuthError):
    """Used to indicate that an refreshing the credentials' access token
    failed."""

    ...

class UserAccessTokenError(GoogleAuthError):
    """Used to indicate ``gcloud auth print-access-token`` command failed."""

    ...

class DefaultCredentialsError(GoogleAuthError):
    """Used to indicate that acquiring default credentials failed."""

    ...

class MutualTLSChannelError(GoogleAuthError):
    """Used to indicate that mutual TLS channel creation is failed, or mutual
    TLS channel credentials is missing or invalid."""

    ...

class ClientCertError(GoogleAuthError):
    """Used to indicate that client certificate is missing or invalid."""

    ...

class OAuthError(GoogleAuthError):
    """Used to indicate an error occurred during an OAuth related HTTP
    request."""

    ...

class ReauthFailError(RefreshError):
    """An exception for when reauth failed."""

    def __init__(self, message=...) -> None: ...

class ReauthSamlChallengeFailError(ReauthFailError):
    """An exception for SAML reauth challenge failures."""

    ...
