name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - services/data_service/**
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies 
        run: |
          pip install poetry
          cd services/data_service
          poetry install
      - name: running pylint
        run: |
          cd services/data_service
          poetry run pylint data_service
          poetry run pylint tests
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies 
        run: |
          pip install poetry
          cd services/data_service
          poetry install
      - name: running black
        run: |
          cd services/data_service
          poetry run black --check .
          
      - run: poetry run black --check .
      
